### PR TITLE
Update gocf

### PR DESCRIPTION
**Pull request by ar-pa**
+ Added support for subtask problems, e. g. A1, A2, ...
+ Using urllib3 instead of urllib2
+ Changed Python version to Python 3
+ Added more parameters to compiler

### CODE REVIEW

**Review by sukeesh — APPROVED** [review]

**Comment by ar-pa** [comment]
@sukeesh check the changes and notify me if there are some problems. Also, can I share a post about this update on Codeforces?

**Comment by sukeesh** [comment]
@ar-pa So sorry for late reply. Code looks good to me. Please feel free to merge. 

> Also, can I share a post about this update on Codeforces?

Ofc, yes!

**Comment by jakobkogler** [comment]
@sukeesh I doubt that ar-pa has merge privileges. You, as the owner, have to do the merge.

**Comment by ar-pa** [comment]
Yes. @sukeesh, I don't have access to merge. Please merge and then I'll post a blog.

**Pull request merged**
